"use client";

import { useState } from "react";
import { CheckIcon, CopyIcon } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { Issue, RunResult } from "@/lib/api";
import { fmt, langLabel } from "@/lib/api";
import { cn } from "@/lib/utils";
import { ChartLegendInline, TelemetryChart } from "./telemetry-chart";
import { EmptyState } from "./states";

export const CATEGORY_LABEL: Record<string, string> = {
  bug: "Bug",
  balance: "Balance",
  skill_issue: "Skill issue",
  noise: "Noise",
};

export function CategoryBadge({ category }: { category: string }) {
  return (
    <Badge
      variant="outline"
      className={cn(
        category === "bug" && "border-loss/40 text-loss",
        category === "balance" && "border-watch/40 text-watch",
        category === "skill_issue" && "border-proof/40 text-proof",
      )}
    >
      {CATEGORY_LABEL[category] ?? category}
    </Badge>
  );
}

export function SeverityBadge({ severity }: { severity?: string | null }) {
  if (!severity) return null;
  return (
    <Badge
      className={cn(
        "capitalize",
        severity === "blocker" && "bg-loss text-background",
        severity === "major" && "bg-loss/20 text-loss",
        severity === "minor" && "bg-muted text-foreground",
        severity === "cosmetic" && "bg-muted text-muted-foreground",
      )}
    >
      {severity}
    </Badge>
  );
}

export function LanguageChips({ languages }: { languages: string[] }) {
  return (
    <div className="flex flex-wrap gap-1">
      {languages.map((l) => (
        <span key={l} className="rounded-md bg-muted px-1.5 py-0.5 font-mono text-[11px] text-muted-foreground">
          {langLabel(l)}
        </span>
      ))}
    </div>
  );
}

export function whereLabel(issue: Pick<Issue, "level" | "level_name">, unit = "level") {
  if (issue.level == null) return `Unknown ${unit}`;
  return issue.level_name ? `${issue.level_name} · ${unit} ${issue.level}` : `${unit} ${issue.level}`;
}

function toMarkdown(issue: Issue, result: RunResult) {
  const t = issue.ticket;
  const lines: string[] = [];
  lines.push(`## ${t?.title ?? issue.title}`, "");
  lines.push(
    `**Priority:** #${issue.priority ?? "–"} · **Type:** ${CATEGORY_LABEL[issue.category]} · **Severity:** ${t?.severity ?? "–"}`,
  );
  lines.push(
    `**Where:** ${whereLabel(issue, result.unit)} · **Players lost (est.):** ${fmt.int(issue.players_lost_estimate)} · **Reports:** ${issue.message_ids.length} from ${issue.distinct_players} players (${issue.languages.map(langLabel).join(", ")})`,
    "",
  );
  if (t?.summary) lines.push(t.summary, "");
  if (issue.telemetry) {
    const { prev, cur } = issue.telemetry;
    lines.push(
      "### Telemetry",
      "",
      `| Metric | ${prev.patch} | ${cur.patch} |`,
      "|---|---|---|",
      `| Completion rate | ${fmt.pct(prev.completion_rate)} | ${fmt.pct(cur.completion_rate)} |`,
      `| Deaths / player | ${fmt.dec(prev.deaths_per_player)} | ${fmt.dec(cur.deaths_per_player)} |`,
      `| Restarts / player | ${fmt.dec(prev.restarts_per_player)} | ${fmt.dec(cur.restarts_per_player)} |`,
      `| Error reports | ${prev.error_reports} | ${cur.error_reports} |`,
      "",
    );
  }
  if (issue.telemetry_evidence) lines.push(`> ${issue.telemetry_evidence}`, "");
  if (t?.suspected_cause) lines.push("### Suspected cause", "", t.suspected_cause, "");
  const steps = t?.repro_steps ?? issue.repro_steps ?? [];
  if (steps.length) {
    lines.push("### Repro steps (inferred from player reports)", "");
    steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    lines.push("");
  }
  if (t?.evidence?.length) {
    lines.push("### Player evidence", "");
    for (const e of t.evidence) {
      lines.push(`> ${e.text}`);
      if (e.english && e.english !== e.text) lines.push(`> _${e.english}_`);
      lines.push("");
    }
  }
  lines.push(`_Generated by PlayerPulse · ${result.model}_`);
  return lines.join("\n");
}

function CopyButton({ issue, result }: { issue: Issue; result: RunResult }) {
  const [copied, setCopied] = useState(false);
  return (
    <Button
      variant="outline"
      size="sm"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(toMarkdown(issue, result));
          setCopied(true);
          setTimeout(() => setCopied(false), 1800);
        } catch {
          /* clipboard unavailable */
        }
      }}
    >
      {copied ? <CheckIcon /> : <CopyIcon />}
      {copied ? "Copied" : "Copy as GitHub issue"}
    </Button>
  );
}

function IssueCard({ issue, result }: { issue: Issue; result: RunResult }) {
  const t = issue.ticket;
  const steps = t?.repro_steps ?? issue.repro_steps ?? [];
  return (
    <article className="rounded-xl bg-card ring-1 ring-foreground/8">
      <header className="flex flex-col gap-4 p-5 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex min-w-0 gap-4">
          <span className="font-mono text-2xl font-semibold tabular-nums text-muted-foreground">
            #{issue.priority ?? "–"}
          </span>
          <div className="min-w-0 space-y-2">
            <h3 className="text-lg font-semibold leading-snug text-balance">{t?.title ?? issue.title}</h3>
            <div className="flex flex-wrap items-center gap-1.5">
              <CategoryBadge category={issue.category} />
              <SeverityBadge severity={t?.severity} />
              <span className="text-sm text-muted-foreground">{whereLabel(issue, result.unit)}</span>
            </div>
          </div>
        </div>
        <div className="flex shrink-0 gap-6 sm:text-right">
          <div>
            <div className="text-3xl font-semibold tabular-nums text-loss">{fmt.int(issue.players_lost_estimate)}</div>
            <div className="text-xs text-muted-foreground">players lost</div>
          </div>
          <div>
            <div className="text-3xl font-semibold tabular-nums">{issue.message_ids.length}</div>
            <div className="text-xs text-muted-foreground">reports · {issue.distinct_players} players</div>
          </div>
        </div>
      </header>

      <div className="grid gap-6 border-t border-border p-5 lg:grid-cols-2">
        <section className="space-y-3">
          <div className="flex items-center justify-between">
            <h4 className="text-sm font-medium">Telemetry</h4>
            <ChartLegendInline />
          </div>
          <TelemetryChart telemetry={issue.telemetry} />
          {issue.telemetry_evidence && <p className="text-sm text-muted-foreground">{issue.telemetry_evidence}</p>}
          <div className="flex items-center gap-2 pt-1">
            <span className="text-xs text-muted-foreground">Reported in</span>
            <LanguageChips languages={issue.languages} />
          </div>
        </section>
        <section className="space-y-4 text-sm">
          {t?.summary && <p className="leading-relaxed">{t.summary}</p>}
          {t?.suspected_cause && (
            <div>
              <h4 className="mb-1 font-medium">Suspected cause</h4>
              <p className="leading-relaxed text-muted-foreground">{t.suspected_cause}</p>
            </div>
          )}
          {steps.length > 0 && (
            <div>
              <h4 className="mb-1 font-medium">
                Repro steps <span className="font-normal text-muted-foreground">inferred from player reports</span>
              </h4>
              <ol className="list-decimal space-y-1 pl-5 text-muted-foreground marker:tabular-nums">
                {steps.map((s, i) => (
                  <li key={i}>{s}</li>
                ))}
              </ol>
            </div>
          )}
        </section>
      </div>

      {t?.evidence && t.evidence.length > 0 && (
        <div className="border-t border-border p-5">
          <h4 className="mb-3 text-sm font-medium">What players said</h4>
          <div className="grid gap-3 md:grid-cols-2">
            {t.evidence.map((e) => (
              <figure key={e.id} className="rounded-lg bg-muted/40 p-3 text-sm">
                <blockquote className="leading-relaxed">“{e.text}”</blockquote>
                {e.english && e.english !== e.text && (
                  <figcaption className="mt-1.5 leading-relaxed text-muted-foreground">{e.english}</figcaption>
                )}
              </figure>
            ))}
          </div>
        </div>
      )}

      <footer className="flex justify-end border-t border-border px-5 py-3">
        <CopyButton issue={issue} result={result} />
      </footer>
    </article>
  );
}

export function IssuesView({ result }: { result: RunResult }) {
  const issues = result.issues
    .filter((i) => i.status === "reported")
    .sort((a, b) => (a.priority ?? 999) - (b.priority ?? 999));
  return (
    <div className="space-y-5">
      {issues.length === 0 ? (
        <EmptyState title="No verified issues in this run" body="Nothing players reported was confirmed as a real problem." />
      ) : (
        issues.map((i, idx) => <IssueCard key={`${i.title}-${idx}`} issue={i} result={result} />)
      )}
      <p className="text-sm text-muted-foreground">
        Priority = players who started the level on the new patch × drop in completion rate
      </p>
    </div>
  );
}
